-- EquaFit initial schema for Supabase/Postgres
-- Run in Supabase SQL editor or via migration tooling.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  height_cm integer,
  weight_kg numeric(5,2),
  age integer,
  gender text check (gender in ('male', 'female', 'other')),
  goals text[] default '{}',
  period_tracking_enabled boolean default false,
  cycle_length_days integer default 28,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.completed_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  group_id text not null,
  day integer not null,
  date date not null,
  feeling text check (feeling in ('great', 'good', 'okay', 'tired')),
  created_at timestamptz not null default now(),
  unique (user_id, group_id, day, date)
);

create table if not exists public.period_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  notes text,
  flow text check (flow in ('light', 'medium', 'heavy')),
  symptoms text[] default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.reminder_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  time text not null default '09:00',
  messages text[] default '{}',
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.completed_days enable row level security;
alter table public.period_entries enable row level security;
alter table public.reminder_settings enable row level security;

create policy "profiles owner access" on public.profiles
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "completed_days owner access" on public.completed_days
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "period_entries owner access" on public.period_entries
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "reminder_settings owner access" on public.reminder_settings
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

