-- Auto-create a profiles row for every new auth user (fixes silent 0-row updates before first profile save).
-- Backfill existing users who signed up before this migration.
-- Weight history for Progress page (was localStorage-only).

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.profiles (user_id)
select u.id from auth.users u
where not exists (select 1 from public.profiles p where p.user_id = u.id);

create table if not exists public.weight_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  weight_kg numeric(5,2) not null check (weight_kg > 0 and weight_kg <= 400),
  created_at timestamptz not null default now(),
  unique (user_id, entry_date)
);

create index if not exists weight_entries_user_date_idx on public.weight_entries (user_id, entry_date desc);

alter table public.weight_entries enable row level security;

drop policy if exists "weight_entries owner access" on public.weight_entries;
create policy "weight_entries owner access" on public.weight_entries
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
